apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-assistant.fullname" . }}-svc-api
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    {{- include "devops-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  type: {{ .Values.api.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
