apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  namespace: devops-assistant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-devops-assistant
          image: ghcr.io/mateus-sebastiao/local-ai-assistant-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: config-assistant
