apiVersion: v1
kind: Service
metadata:
  name: service-ollama
  namespace: devops-assistant
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP